#include <reasoner/reasoner.hh>
namespace ares
{
    const char* Reasoner::ROLE_QUERY        = "(role ?r)";
    const char* Reasoner::INIT_QUERY        = "(init ?x) ";
    const char* Reasoner::LEGAL_QUERY       = "(legal ?r ?x)";
    const char* Reasoner::NEXT_QUERY        = "(next ?x)";
    const char* Reasoner::GOAL_QUERY        = "(goal ?r ?x)";
    const char* Reasoner::TRUE_QUERY        = "(true ?x)";
    const char* Reasoner::TERMINAL_QUERY    = "terminal";
    

    typedef std::shared_ptr<CallBack> SharedCB;
    void Reasoner::query(const Clause* goal,const State* context,SharedCB cb,bool rand){
        auto g = std::unique_ptr<Clause>(goal->clone());
        g->setSubstitution(new Substitution());
        auto cache = std::unique_ptr<Cache>( new Cache( rand ? AnsIterator::RAND : AnsIterator::SEQ ));
        Query query(g, cb,context,cache.get(),0,rand);
        query.pool = ThreadPoolFactroy::get(cfg.proverThreads);
        prover.compute(query);
        ThreadPoolFactroy::deallocate(query.pool);
    }
    void printCacheStat(const Clause* goal, Cache* cache){
        std::cout << "------- Cache Statistics "<< goal->to_string() << "------- \n" ;
        std::cout <<" Total Lookups : " << cache->nlookups<<"\n";
        std::cout <<" Total SolutionNodes : " << cache->nsolns<<"\n";
        std::cout <<" Total Consumed Answer : " << cache->nconsumedAns<<"\n";
        std::cout <<" Total New Answers : " << cache->nnewAns<<"\n";
        if( cache->nsolns)
            std::cout <<" Average Answer generated by a Solution Node : " << (cache->nnewAns/cache->nsolns)<<"\n";
        if( cache->nlookups)
            std::cout <<" Average Consumed Answer by a Lookup Node : " << (cache->nconsumedAns/cache->nlookups)<<"\n";
    }
    State* Reasoner::next(const State& state,const Action& moves){
        auto& roles = game->getRoles();
        State* context = new State();
        (*context) += state;            //Shallow copy
        PoolKey key;
        for (size_t i = 0; i < moves.size(); i++)
        {
            Body* body = new Body{roles[i], moves[i]};
            key = PoolKey{Namer::DOES, body,true};
            auto l = memCache.getLiteral(key);
            context->add(Namer::DOES, new Clause(l,new ClauseBody(0)));           //This is thread safe
        }
        auto cb = std::shared_ptr<NxtCallBack>(new NxtCallBack(this, new State()));
        query(NEXT_GOAL, context, cb);
        
        for (auto &&d : *(*context)[Namer::DOES])
            delete d;

        delete (*context)[Namer::DOES];
        
        context->reset();
        delete context;
        
        return cb->newState;
    }

    Moves* Reasoner::moves(const State& state,const Role& role,bool rand){
        const auto& legal = roleLegalMap[role.get_name()].get();        //Get the legal query specific to this role 
        auto cb = std::shared_ptr<LegalCallBack>(new LegalCallBack(this,rand));
        query(legal, &state, cb,rand);
        return cb->moves;
    }
    
    bool Reasoner::terminal(const State& state){
        auto cb = std::shared_ptr<TerminalCallBack>(new TerminalCallBack());
        query(TERMINAL_GOAL, &state,cb);
        return cb->terminal;
    }
    
    float Reasoner::reward(Role& role, const State* state){
        const auto& goal = roleGoalMap[role.get_name()].get();        //Get the query specific to this role
        auto cb = std::shared_ptr<RewardCallBack>(new RewardCallBack(this));
        query(goal, state, cb);
        return cb->reward;
    }

    /**
     *Helper Functions.
     */
    move_sptr Reasoner::randMove(const State& state,const Role& role){
        auto* legals = moves(state, role);
        uint i = rand() % legals->size();
        auto selected = (*legals)[i];
        delete legals;
        return selected;
    }

    Action* Reasoner::randAction(const State& state){
        Action* action = new Action();
        for (auto &&role : roles())
            action->push_back( randMove(state,*role));
        return action;
    }
    
    std::vector<uAction>* Reasoner::actions(const State& state){
        const auto& roles = this->roles();
        std::vector<uMoves> legals;
        for (auto &&r : roles)
            legals.push_back( uMoves(moves(state, *r)));

        Moves partials;
        std::vector<uAction>* combos= new std::vector<uAction>();
        getCombos(legals, 0,partials,*combos);
        return combos;
    }

    void Reasoner::initMapping(){
        auto& roles = game->getRoles();
        if( roleLegalMap.size() > 0) return;

        for (size_t i = 0; i < roles.size(); i++)
            rolesIndex[roles[i]->get_name()] = i;        //from the name to its index
        
        /**
         * Template for (legal some_role ?x) and (goal some_role ?x)
         */
        auto& template_body_legal = LEGAL_GOAL->front()->getBody();
        auto& template_body_goal = GOAL_GOAL->front()->getBody();

        PoolKey key_legal{Namer::LEGAL, nullptr, true};
        PoolKey key_goal{Namer::GOAL, nullptr, true};


        for (auto &&r : roles)
        {
            //Init legal query for role
            key_legal.body = new Body(template_body_legal.begin(), template_body_legal.end());
            (*(Body*)key_legal.body)[0] = r;
            const cnst_lit_sptr& legal_l = memCache.getLiteral(key_legal);
            roleLegalMap[r->get_name()].reset(new Clause(nullptr, new ClauseBody{legal_l}));
            
            //Init goal query for role
            key_goal.body = new Body(template_body_goal.begin(), template_body_goal.end());;
            (*(Body*)key_goal.body)[0] = r;
            const cnst_lit_sptr& goal_l = memCache.getLiteral(key_goal);
            roleGoalMap[r->get_name()].reset(new Clause(nullptr, new ClauseBody{goal_l}));
        }
    }

} // namespace ares
